# random forest classifer

from tree import training_data, training_labels, testing_data, testing_labels, make_random_forest, make_single_tree, classify
import numpy as np
import random
np.random.seed(1)
random.seed(1)

tree = make_single_tree(training_data, training_labels)
forest = make_random_forest(40,training_data,training_labels)
forest_correct =0
single_tree_correct = 0

for i in range(len(testing_data)):
  prediction = classify(testing_data[i], tree)
  if prediction == testing_labels[i]:
    single_tree_correct += 1
  predictions = []
  for forest_tree in forest:
    predictions.append(classify(testing_data[i],forest_tree))
  forest_prediction = max(predictions,key=predictions.count)  
  if forest_prediction == testing_labels[i]:
    forest_correct +=1  

print(single_tree_correct/len(testing_data))
print(forest_correct/len(testing_data))

# random forest and single tree

import operator
from collections import Counter
import random
import numpy as np
np.random.seed(1)
random.seed(1)

def split(dataset, labels, column):
    data_subsets = []
    label_subsets = []
    counts = list(set([data[column] for data in dataset]))
    counts.sort()
    for k in counts:
        new_data_subset = []
        new_label_subset = []
        for i in range(len(dataset)):
            if dataset[i][column] == k:
                new_data_subset.append(dataset[i])
                new_label_subset.append(labels[i])
        data_subsets.append(new_data_subset)
        label_subsets.append(new_label_subset)
    return data_subsets, label_subsets

def gini(dataset):
  impurity = 1
  label_counts = Counter(dataset)
  for label in label_counts:
    prob_of_label = label_counts[label] / len(dataset)
    impurity -= prob_of_label ** 2
  return impurity

def information_gain(starting_labels, split_labels):
  info_gain = gini(starting_labels)
  for subset in split_labels:
    info_gain -= gini(subset) * len(subset)/len(starting_labels)
  return info_gain

class Leaf:
    def __init__(self, labels, value):
        self.labels = Counter(labels)
        self.value = value

class Internal_Node:
    def __init__(self,
                 feature,
                 branches,
                 value):
        self.feature = feature
        self.branches = branches
        self.value = value

def find_best_split_subset(dataset, labels, num_features):
    features = np.random.choice(6, 3, replace=False)
    best_gain = 0
    best_feature = 0
    for feature in features:
        data_subsets, label_subsets = split(dataset, labels, feature)
        gain = information_gain(labels, label_subsets)
        if gain > best_gain:
            best_gain, best_feature = gain, feature
    return best_feature, best_gain

def find_best_split(dataset, labels):
    best_gain = 0
    best_feature = 0
    for feature in range(len(dataset[0])):
        data_subsets, label_subsets = split(dataset, labels, feature)
        gain = information_gain(labels, label_subsets)
        if gain > best_gain:
            best_gain, best_feature = gain, feature
    return best_feature, best_gain

def make_single_tree(data, labels, value = ""):
  best_feature, best_gain = find_best_split(data, labels)
  if best_gain < 0.00000001:
    return Leaf(Counter(labels), value)
  data_subsets, label_subsets = split(data, labels, best_feature)
  branches = []
  for i in range(len(data_subsets)):
    branch = make_single_tree(data_subsets[i], label_subsets[i], data_subsets[i][0][best_feature])
    branches.append(branch)
  return Internal_Node(best_feature, branches, value)

def build_tree_forest(data,labels, n_features, value=""):
    best_feature, best_gain = find_best_split_subset(data, labels, n_features)
    if best_gain < 0.00000001:
      return Leaf(Counter(labels), value)
    data_subsets, label_subsets = split(data, labels, best_feature)
    branches = []
    for i in range(len(data_subsets)):
      branch = build_tree_forest(data_subsets[i], label_subsets[i], n_features, data_subsets[i][0][best_feature])
      branches.append(branch)
    return Internal_Node(best_feature, branches, value)

def print_tree(node, spacing=""):
    """World's most elegant tree printing function."""
    question_dict = {0: "Buying Price", 1:"Price of maintenance", 2:"Number of doors", 3:"Person Capacity", 4:"Size of luggage boot", 5:"Estimated Saftey"}
    # Base case: we've reached a leaf
    if isinstance(node, Leaf):
        print (spacing + str(node.labels))
        return

    # Print the question at this node
    print (spacing + "Splitting on " + question_dict[node.feature])

    # Call this function recursively on the true branch
    for i in range(len(node.branches)):
        print (spacing + '--> Branch ' + node.branches[i].value+':')
        print_tree(node.branches[i], spacing + "  ")

def make_cars():
    f = open("car.data", "r")
    cars = []
    for line in f:
        cars.append(line.rstrip().split(","))
    return cars

def change_data(data):
    dicts = [{'vhigh' : 1.0, 'high' : 2.0, 'med' : 3.0, 'low' : 4.0},
    {'vhigh' : 1.0, 'high' : 2.0, 'med' : 3.0, 'low' : 4.0},
    {'2' : 1.0, '3' : 2.0, '4' : 3.0, '5more' : 4.0},
    {'2' : 1.0, '4' : 2.0, 'more' : 3.0},
    {'small' : 1.0, 'med' : 2.0, 'big' : 3.0},
    {'low' : 1.0, 'med' : 2.0, 'high' : 3.0}]

    for row in data:
        for i in range(len(dicts)):
            row[i] = dicts[i][row[i]]

    return data


def classify(datapoint, tree):
  if isinstance(tree, Leaf):
    items = list(tree.labels.items()) 
    items.sort()
    return max(items, key=operator.itemgetter(1))[0]

  value = datapoint[tree.feature]
  for branch in tree.branches:
    if branch.value == value:
      return classify(datapoint, branch)
  #return classify(datapoint, tree.branches[random.randint(0, len(tree.branches)-1)])


cars = make_cars()
random.shuffle(cars)
car_data = [x[:-1] for x in cars]
car_labels = [x[-1] for x in cars]
# car_data = car_data[:500]
# car_labels = car_labels[:500]


training_data = car_data[:int(len(car_data)*0.8)]
training_labels = car_labels[:int(len(car_data)*0.8)]

testing_data = car_data[int(len(car_data)*0.8):]
testing_labels = car_labels[int(len(car_data)*0.8):]

def make_random_forest(n, training_data, training_labels):
    trees = []
    for i in range(n):
        indices = [random.randint(0, len(training_data)-1) for x in range(len(training_data))]

        training_data_subset = [training_data[index] for index in indices]
        training_labels_subset = [training_labels[index] for index in indices]

        tree = build_tree_forest(training_data_subset, training_labels_subset, 2)
        trees.append(tree)
    return trees

# data_file used in classifier

vhigh,vhigh,2,2,small,low,unacc
vhigh,vhigh,2,2,small,med,unacc
vhigh,vhigh,2,2,small,high,unacc
vhigh,vhigh,2,2,med,low,unacc
vhigh,vhigh,2,2,med,med,unacc
vhigh,vhigh,2,2,med,high,unacc
vhigh,vhigh,2,2,big,low,unacc
vhigh,vhigh,2,2,big,med,unacc
vhigh,vhigh,2,2,big,high,unacc
vhigh,vhigh,2,4,small,low,unacc
vhigh,vhigh,2,4,small,med,unacc
vhigh,vhigh,2,4,small,high,unacc
vhigh,vhigh,2,4,med,low,unacc
vhigh,vhigh,2,4,med,med,unacc
vhigh,vhigh,2,4,med,high,unacc
vhigh,vhigh,2,4,big,low,unacc
vhigh,vhigh,2,4,big,med,unacc
vhigh,vhigh,2,4,big,high,unacc
vhigh,vhigh,2,more,small,low,unacc
vhigh,vhigh,2,more,small,med,unacc
vhigh,vhigh,2,more,small,high,unacc
vhigh,vhigh,2,more,med,low,unacc
vhigh,vhigh,2,more,med,med,unacc
vhigh,vhigh,2,more,med,high,unacc
vhigh,vhigh,2,more,big,low,unacc
vhigh,vhigh,2,more,big,med,unacc
vhigh,vhigh,2,more,big,high,unacc
vhigh,vhigh,3,2,small,low,unacc
vhigh,vhigh,3,2,small,med,unacc
vhigh,vhigh,3,2,small,high,unacc
vhigh,vhigh,3,2,med,low,unacc
vhigh,vhigh,3,2,med,med,unacc
vhigh,vhigh,3,2,med,high,unacc
vhigh,vhigh,3,2,big,low,unacc
vhigh,vhigh,3,2,big,med,unacc
vhigh,vhigh,3,2,big,high,unacc
vhigh,vhigh,3,4,small,low,unacc
vhigh,vhigh,3,4,small,med,unacc
vhigh,vhigh,3,4,small,high,unacc
vhigh,vhigh,3,4,med,low,unacc
vhigh,vhigh,3,4,med,med,unacc
vhigh,vhigh,3,4,med,high,unacc
vhigh,vhigh,3,4,big,low,unacc
vhigh,vhigh,3,4,big,med,unacc
vhigh,vhigh,3,4,big,high,unacc
vhigh,vhigh,3,more,small,low,unacc
vhigh,vhigh,3,more,small,med,unacc
vhigh,vhigh,3,more,small,high,unacc
vhigh,vhigh,3,more,med,low,unacc
vhigh,vhigh,3,more,med,med,unacc
vhigh,vhigh,3,more,med,high,unacc
vhigh,vhigh,3,more,big,low,unacc
vhigh,vhigh,3,more,big,med,unacc
vhigh,vhigh,3,more,big,high,unacc
vhigh,vhigh,4,2,small,low,unacc
vhigh,vhigh,4,2,small,med,unacc
vhigh,vhigh,4,2,small,high,unacc
vhigh,vhigh,4,2,med,low,unacc
vhigh,vhigh,4,2,med,med,unacc
vhigh,vhigh,4,2,med,high,unacc
vhigh,vhigh,4,2,big,low,unacc
vhigh,vhigh,4,2,big,med,unacc
vhigh,vhigh,4,2,big,high,unacc
vhigh,vhigh,4,4,small,low,unacc
vhigh,vhigh,4,4,small,med,unacc
vhigh,vhigh,4,4,small,high,unacc
vhigh,vhigh,4,4,med,low,unacc
vhigh,vhigh,4,4,med,med,unacc
vhigh,vhigh,4,4,med,high,unacc
vhigh,vhigh,4,4,big,low,unacc
vhigh,vhigh,4,4,big,med,unacc
vhigh,vhigh,4,4,big,high,unacc
vhigh,vhigh,4,more,small,low,unacc
vhigh,vhigh,4,more,small,med,unacc
vhigh,vhigh,4,more,small,high,unacc
vhigh,vhigh,4,more,med,low,unacc
vhigh,vhigh,4,more,med,med,unacc
vhigh,vhigh,4,more,med,high,unacc
vhigh,vhigh,4,more,big,low,unacc
vhigh,vhigh,4,more,big,med,unacc
vhigh,vhigh,4,more,big,high,unacc
vhigh,vhigh,5more,2,small,low,unacc
vhigh,vhigh,5more,2,small,med,unacc
vhigh,vhigh,5more,2,small,high,unacc
vhigh,vhigh,5more,2,med,low,unacc
vhigh,vhigh,5more,2,med,med,unacc
vhigh,vhigh,5more,2,med,high,unacc
vhigh,vhigh,5more,2,big,low,unacc
vhigh,vhigh,5more,2,big,med,unacc
vhigh,vhigh,5more,2,big,high,unacc
vhigh,vhigh,5more,4,small,low,unacc
vhigh,vhigh,5more,4,small,med,unacc
vhigh,vhigh,5more,4,small,high,unacc
vhigh,vhigh,5more,4,med,low,unacc
vhigh,vhigh,5more,4,med,med,unacc
vhigh,vhigh,5more,4,med,high,unacc
vhigh,vhigh,5more,4,big,low,unacc
vhigh,vhigh,5more,4,big,med,unacc
vhigh,vhigh,5more,4,big,high,unacc
vhigh,vhigh,5more,more,small,low,unacc
vhigh,vhigh,5more,more,small,med,unacc
vhigh,vhigh,5more,more,small,high,unacc
vhigh,vhigh,5more,more,med,low,unacc
vhigh,vhigh,5more,more,med,med,unacc
vhigh,vhigh,5more,more,med,high,unacc
vhigh,vhigh,5more,more,big,low,unacc
vhigh,vhigh,5more,more,big,med,unacc
vhigh,vhigh,5more,more,big,high,unacc
vhigh,high,2,2,small,low,unacc
vhigh,high,2,2,small,med,unacc
vhigh,high,2,2,small,high,unacc
vhigh,high,2,2,med,low,unacc
vhigh,high,2,2,med,med,unacc
vhigh,high,2,2,med,high,unacc
vhigh,high,2,2,big,low,unacc
vhigh,high,2,2,big,med,unacc
vhigh,high,2,2,big,high,unacc
vhigh,high,2,4,small,low,unacc
vhigh,high,2,4,small,med,unacc
vhigh,high,2,4,small,high,unacc
vhigh,high,2,4,med,low,unacc
vhigh,high,2,4,med,med,unacc
vhigh,high,2,4,med,high,unacc
vhigh,high,2,4,big,low,unacc
vhigh,high,2,4,big,med,unacc
vhigh,high,2,4,big,high,unacc
vhigh,high,2,more,small,low,unacc
vhigh,high,2,more,small,med,unacc
vhigh,high,2,more,small,high,unacc
vhigh,high,2,more,med,low,unacc
vhigh,high,2,more,med,med,unacc
vhigh,high,2,more,med,high,unacc
vhigh,high,2,more,big,low,unacc
vhigh,high,2,more,big,med,unacc
vhigh,high,2,more,big,high,unacc
vhigh,high,3,2,small,low,unacc
vhigh,high,3,2,small,med,unacc
vhigh,high,3,2,small,high,unacc
vhigh,high,3,2,med,low,unacc
vhigh,high,3,2,med,med,unacc
vhigh,high,3,2,med,high,unacc
vhigh,high,3,2,big,low,unacc
vhigh,high,3,2,big,med,unacc
vhigh,high,3,2,big,high,unacc
vhigh,high,3,4,small,low,unacc
vhigh,high,3,4,small,med,unacc
vhigh,high,3,4,small,high,unacc
vhigh,high,3,4,med,low,unacc
vhigh,high,3,4,med,med,unacc
vhigh,high,3,4,med,high,unacc
vhigh,high,3,4,big,low,unacc
vhigh,high,3,4,big,med,unacc
vhigh,high,3,4,big,high,unacc
vhigh,high,3,more,small,low,unacc
vhigh,high,3,more,small,med,unacc
vhigh,high,3,more,small,high,unacc
vhigh,high,3,more,med,low,unacc
vhigh,high,3,more,med,med,unacc
vhigh,high,3,more,med,high,unacc
vhigh,high,3,more,big,low,unacc
vhigh,high,3,more,big,med,unacc
vhigh,high,3,more,big,high,unacc
vhigh,high,4,2,small,low,unacc
vhigh,high,4,2,small,med,unacc
vhigh,high,4,2,small,high,unacc
vhigh,high,4,2,med,low,unacc
vhigh,high,4,2,med,med,unacc
vhigh,high,4,2,med,high,unacc
vhigh,high,4,2,big,low,unacc
vhigh,high,4,2,big,med,unacc
vhigh,high,4,2,big,high,unacc
vhigh,high,4,4,small,low,unacc
vhigh,high,4,4,small,med,unacc
vhigh,high,4,4,small,high,unacc
vhigh,high,4,4,med,low,unacc
vhigh,high,4,4,med,med,unacc
vhigh,high,4,4,med,high,unacc
vhigh,high,4,4,big,low,unacc
vhigh,high,4,4,big,med,unacc
vhigh,high,4,4,big,high,unacc
vhigh,high,4,more,small,low,unacc
vhigh,high,4,more,small,med,unacc
vhigh,high,4,more,small,high,unacc
vhigh,high,4,more,med,low,unacc
vhigh,high,4,more,med,med,unacc
vhigh,high,4,more,med,high,unacc
vhigh,high,4,more,big,low,unacc
vhigh,high,4,more,big,med,unacc
vhigh,high,4,more,big,high,unacc
vhigh,high,5more,2,small,low,unacc
vhigh,high,5more,2,small,med,unacc
vhigh,high,5more,2,small,high,unacc
vhigh,high,5more,2,med,low,unacc
vhigh,high,5more,2,med,med,unacc
vhigh,high,5more,2,med,high,unacc
vhigh,high,5more,2,big,low,unacc
vhigh,high,5more,2,big,med,unacc
vhigh,high,5more,2,big,high,unacc
vhigh,high,5more,4,small,low,unacc
vhigh,high,5more,4,small,med,unacc
vhigh,high,5more,4,small,high,unacc
vhigh,high,5more,4,med,low,unacc
vhigh,high,5more,4,med,med,unacc
vhigh,high,5more,4,med,high,unacc
vhigh,high,5more,4,big,low,unacc
vhigh,high,5more,4,big,med,unacc
vhigh,high,5more,4,big,high,unacc
vhigh,high,5more,more,small,low,unacc
vhigh,high,5more,more,small,med,unacc
vhigh,high,5more,more,small,high,unacc
vhigh,high,5more,more,med,low,unacc
vhigh,high,5more,more,med,med,unacc
vhigh,high,5more,more,med,high,unacc
vhigh,high,5more,more,big,low,unacc
vhigh,high,5more,more,big,med,unacc
vhigh,high,5more,more,big,high,unacc
vhigh,med,2,2,small,low,unacc
vhigh,med,2,2,small,med,unacc
vhigh,med,2,2,small,high,unacc
vhigh,med,2,2,med,low,unacc
vhigh,med,2,2,med,med,unacc
vhigh,med,2,2,med,high,unacc
vhigh,med,2,2,big,low,unacc
vhigh,med,2,2,big,med,unacc
vhigh,med,2,2,big,high,unacc
vhigh,med,2,4,small,low,unacc
vhigh,med,2,4,small,med,unacc
vhigh,med,2,4,small,high,acc
vhigh,med,2,4,med,low,unacc
vhigh,med,2,4,med,med,unacc
vhigh,med,2,4,med,high,acc
vhigh,med,2,4,big,low,unacc
vhigh,med,2,4,big,med,acc
vhigh,med,2,4,big,high,acc
vhigh,med,2,more,small,low,unacc
vhigh,med,2,more,small,med,unacc
vhigh,med,2,more,small,high,unacc
vhigh,med,2,more,med,low,unacc
vhigh,med,2,more,med,med,unacc
vhigh,med,2,more,med,high,acc
vhigh,med,2,more,big,low,unacc
vhigh,med,2,more,big,med,acc
vhigh,med,2,more,big,high,acc
vhigh,med,3,2,small,low,unacc
vhigh,med,3,2,small,med,unacc
vhigh,med,3,2,small,high,unacc
vhigh,med,3,2,med,low,unacc
vhigh,med,3,2,med,med,unacc
vhigh,med,3,2,med,high,unacc
vhigh,med,3,2,big,low,unacc
vhigh,med,3,2,big,med,unacc
vhigh,med,3,2,big,high,unacc
vhigh,med,3,4,small,low,unacc
vhigh,med,3,4,small,med,unacc
vhigh,med,3,4,small,high,acc
vhigh,med,3,4,med,low,unacc
vhigh,med,3,4,med,med,unacc
vhigh,med,3,4,med,high,acc
vhigh,med,3,4,big,low,unacc
vhigh,med,3,4,big,med,acc
vhigh,med,3,4,big,high,acc
vhigh,med,3,more,small,low,unacc
vhigh,med,3,more,small,med,unacc
vhigh,med,3,more,small,high,acc
vhigh,med,3,more,med,low,unacc
vhigh,med,3,more,med,med,acc
vhigh,med,3,more,med,high,acc
vhigh,med,3,more,big,low,unacc
vhigh,med,3,more,big,med,acc
vhigh,med,3,more,big,high,acc
vhigh,med,4,2,small,low,unacc
vhigh,med,4,2,small,med,unacc
vhigh,med,4,2,small,high,unacc
vhigh,med,4,2,med,low,unacc
vhigh,med,4,2,med,med,unacc
vhigh,med,4,2,med,high,unacc
vhigh,med,4,2,big,low,unacc
vhigh,med,4,2,big,med,unacc
vhigh,med,4,2,big,high,unacc
vhigh,med,4,4,small,low,unacc
vhigh,med,4,4,small,med,unacc
vhigh,med,4,4,small,high,acc
vhigh,med,4,4,med,low,unacc
vhigh,med,4,4,med,med,acc
vhigh,med,4,4,med,high,acc
vhigh,med,4,4,big,low,unacc
vhigh,med,4,4,big,med,acc
vhigh,med,4,4,big,high,acc
vhigh,med,4,more,small,low,unacc
vhigh,med,4,more,small,med,unacc
vhigh,med,4,more,small,high,acc
vhigh,med,4,more,med,low,unacc
vhigh,med,4,more,med,med,acc
vhigh,med,4,more,med,high,acc
vhigh,med,4,more,big,low,unacc
vhigh,med,4,more,big,med,acc
vhigh,med,4,more,big,high,acc
vhigh,med,5more,2,small,low,unacc
vhigh,med,5more,2,small,med,unacc
vhigh,med,5more,2,small,high,unacc
vhigh,med,5more,2,med,low,unacc
vhigh,med,5more,2,med,med,unacc
vhigh,med,5more,2,med,high,unacc
vhigh,med,5more,2,big,low,unacc
vhigh,med,5more,2,big,med,unacc
vhigh,med,5more,2,big,high,unacc
vhigh,med,5more,4,small,low,unacc
vhigh,med,5more,4,small,med,unacc
vhigh,med,5more,4,small,high,acc
vhigh,med,5more,4,med,low,unacc
vhigh,med,5more,4,med,med,acc
vhigh,med,5more,4,med,high,acc
vhigh,med,5more,4,big,low,unacc
vhigh,med,5more,4,big,med,acc
vhigh,med,5more,4,big,high,acc
vhigh,med,5more,more,small,low,unacc
vhigh,med,5more,more,small,med,unacc
vhigh,med,5more,more,small,high,acc
vhigh,med,5more,more,med,low,unacc
vhigh,med,5more,more,med,med,acc
vhigh,med,5more,more,med,high,acc
vhigh,med,5more,more,big,low,unacc
vhigh,med,5more,more,big,med,acc
vhigh,med,5more,more,big,high,acc
vhigh,low,2,2,small,low,unacc
vhigh,low,2,2,small,med,unacc
vhigh,low,2,2,small,high,unacc
vhigh,low,2,2,med,low,unacc
vhigh,low,2,2,med,med,unacc
vhigh,low,2,2,med,high,unacc
vhigh,low,2,2,big,low,unacc
vhigh,low,2,2,big,med,unacc
vhigh,low,2,2,big,high,unacc
vhigh,low,2,4,small,low,unacc
vhigh,low,2,4,small,med,unacc
vhigh,low,2,4,small,high,acc
vhigh,low,2,4,med,low,unacc
vhigh,low,2,4,med,med,unacc
vhigh,low,2,4,med,high,acc
vhigh,low,2,4,big,low,unacc
vhigh,low,2,4,big,med,acc
vhigh,low,2,4,big,high,acc
vhigh,low,2,more,small,low,unacc
vhigh,low,2,more,small,med,unacc
vhigh,low,2,more,small,high,unacc
vhigh,low,2,more,med,low,unacc
vhigh,low,2,more,med,med,unacc
vhigh,low,2,more,med,high,acc
vhigh,low,2,more,big,low,unacc
vhigh,low,2,more,big,med,acc
vhigh,low,2,more,big,high,acc
vhigh,low,3,2,small,low,unacc
vhigh,low,3,2,small,med,unacc
vhigh,low,3,2,small,high,unacc
vhigh,low,3,2,med,low,unacc
vhigh,low,3,2,med,med,unacc
vhigh,low,3,2,med,high,unacc
vhigh,low,3,2,big,low,unacc
vhigh,low,3,2,big,med,unacc
vhigh,low,3,2,big,high,unacc
vhigh,low,3,4,small,low,unacc
vhigh,low,3,4,small,med,unacc
vhigh,low,3,4,small,high,acc
vhigh,low,3,4,med,low,unacc
vhigh,low,3,4,med,med,unacc
vhigh,low,3,4,med,high,acc
vhigh,low,3,4,big,low,unacc
vhigh,low,3,4,big,med,acc
vhigh,low,3,4,big,high,acc
vhigh,low,3,more,small,low,unacc
vhigh,low,3,more,small,med,unacc
vhigh,low,3,more,small,high,acc
vhigh,low,3,more,med,low,unacc
vhigh,low,3,more,med,med,acc
vhigh,low,3,more,med,high,acc
vhigh,low,3,more,big,low,unacc
vhigh,low,3,more,big,med,acc
vhigh,low,3,more,big,high,acc
vhigh,low,4,2,small,low,unacc
vhigh,low,4,2,small,med,unacc
vhigh,low,4,2,small,high,unacc
vhigh,low,4,2,med,low,unacc
vhigh,low,4,2,med,med,unacc
vhigh,low,4,2,med,high,unacc
vhigh,low,4,2,big,low,unacc
vhigh,low,4,2,big,med,unacc
vhigh,low,4,2,big,high,unacc
vhigh,low,4,4,small,low,unacc
vhigh,low,4,4,small,med,unacc
vhigh,low,4,4,small,high,acc
vhigh,low,4,4,med,low,unacc
vhigh,low,4,4,med,med,acc
vhigh,low,4,4,med,high,acc
vhigh,low,4,4,big,low,unacc
vhigh,low,4,4,big,med,acc
vhigh,low,4,4,big,high,acc
vhigh,low,4,more,small,low,unacc
vhigh,low,4,more,small,med,unacc
vhigh,low,4,more,small,high,acc
vhigh,low,4,more,med,low,unacc
vhigh,low,4,more,med,med,acc
vhigh,low,4,more,med,high,acc
vhigh,low,4,more,big,low,unacc
vhigh,low,4,more,big,med,acc
vhigh,low,4,more,big,high,acc
vhigh,low,5more,2,small,low,unacc
vhigh,low,5more,2,small,med,unacc
vhigh,low,5more,2,small,high,unacc
vhigh,low,5more,2,med,low,unacc
vhigh,low,5more,2,med,med,unacc
vhigh,low,5more,2,med,high,unacc
vhigh,low,5more,2,big,low,unacc
vhigh,low,5more,2,big,med,unacc
vhigh,low,5more,2,big,high,unacc
vhigh,low,5more,4,small,low,unacc
vhigh,low,5more,4,small,med,unacc
vhigh,low,5more,4,small,high,acc
vhigh,low,5more,4,med,low,unacc
vhigh,low,5more,4,med,med,acc
vhigh,low,5more,4,med,high,acc
vhigh,low,5more,4,big,low,unacc
vhigh,low,5more,4,big,med,acc
vhigh,low,5more,4,big,high,acc
vhigh,low,5more,more,small,low,unacc
vhigh,low,5more,more,small,med,unacc
vhigh,low,5more,more,small,high,acc
vhigh,low,5more,more,med,low,unacc
vhigh,low,5more,more,med,med,acc
vhigh,low,5more,more,med,high,acc
vhigh,low,5more,more,big,low,unacc
vhigh,low,5more,more,big,med,acc
vhigh,low,5more,more,big,high,acc
high,vhigh,2,2,small,low,unacc
high,vhigh,2,2,small,med,unacc
high,vhigh,2,2,small,high,unacc
high,vhigh,2,2,med,low,unacc
high,vhigh,2,2,med,med,unacc
high,vhigh,2,2,med,high,unacc
high,vhigh,2,2,big,low,unacc
high,vhigh,2,2,big,med,unacc
high,vhigh,2,2,big,high,unacc
high,vhigh,2,4,small,low,unacc
high,vhigh,2,4,small,med,unacc
high,vhigh,2,4,small,high,unacc
high,vhigh,2,4,med,low,unacc
high,vhigh,2,4,med,med,unacc
high,vhigh,2,4,med,high,unacc
high,vhigh,2,4,big,low,unacc
high,vhigh,2,4,big,med,unacc
high,vhigh,2,4,big,high,unacc
high,vhigh,2,more,small,low,unacc
high,vhigh,2,more,small,med,unacc
high,vhigh,2,more,small,high,unacc
high,vhigh,2,more,med,low,unacc
high,vhigh,2,more,med,med,unacc
high,vhigh,2,more,med,high,unacc
high,vhigh,2,more,big,low,unacc
high,vhigh,2,more,big,med,unacc
high,vhigh,2,more,big,high,unacc
high,vhigh,3,2,small,low,unacc
high,vhigh,3,2,small,med,unacc
high,vhigh,3,2,small,high,unacc
high,vhigh,3,2,med,low,unacc
high,vhigh,3,2,med,med,unacc
high,vhigh,3,2,med,high,unacc
high,vhigh,3,2,big,low,unacc
high,vhigh,3,2,big,med,unacc
high,vhigh,3,2,big,high,unacc
high,vhigh,3,4,small,low,unacc
high,vhigh,3,4,small,med,unacc
high,vhigh,3,4,small,high,unacc
high,vhigh,3,4,med,low,unacc
high,vhigh,3,4,med,med,unacc
high,vhigh,3,4,med,high,unacc
high,vhigh,3,4,big,low,unacc
high,vhigh,3,4,big,med,unacc
high,vhigh,3,4,big,high,unacc
high,vhigh,3,more,small,low,unacc
high,vhigh,3,more,small,med,unacc
high,vhigh,3,more,small,high,unacc
high,vhigh,3,more,med,low,unacc
high,vhigh,3,more,med,med,unacc
high,vhigh,3,more,med,high,unacc
high,vhigh,3,more,big,low,unacc
high,vhigh,3,more,big,med,unacc
high,vhigh,3,more,big,high,unacc
high,vhigh,4,2,small,low,unacc
high,vhigh,4,2,small,med,unacc
high,vhigh,4,2,small,high,unacc
high,vhigh,4,2,med,low,unacc
high,vhigh,4,2,med,med,unacc
high,vhigh,4,2,med,high,unacc
high,vhigh,4,2,big,low,unacc
high,vhigh,4,2,big,med,unacc
high,vhigh,4,2,big,high,unacc
high,vhigh,4,4,small,low,unacc
high,vhigh,4,4,small,med,unacc
high,vhigh,4,4,small,high,unacc
high,vhigh,4,4,med,low,unacc
high,vhigh,4,4,med,med,unacc
high,vhigh,4,4,med,high,unacc
high,vhigh,4,4,big,low,unacc
high,vhigh,4,4,big,med,unacc
high,vhigh,4,4,big,high,unacc
high,vhigh,4,more,small,low,unacc
high,vhigh,4,more,small,med,unacc
high,vhigh,4,more,small,high,unacc
high,vhigh,4,more,med,low,unacc
high,vhigh,4,more,med,med,unacc
high,vhigh,4,more,med,high,unacc
high,vhigh,4,more,big,low,unacc
high,vhigh,4,more,big,med,unacc
high,vhigh,4,more,big,high,unacc
high,vhigh,5more,2,small,low,unacc
high,vhigh,5more,2,small,med,unacc
high,vhigh,5more,2,small,high,unacc
high,vhigh,5more,2,med,low,unacc
high,vhigh,5more,2,med,med,unacc
high,vhigh,5more,2,med,high,unacc
high,vhigh,5more,2,big,low,unacc
high,vhigh,5more,2,big,med,unacc
high,vhigh,5more,2,big,high,unacc
high,vhigh,5more,4,small,low,unacc
high,vhigh,5more,4,small,med,unacc
high,vhigh,5more,4,small,high,unacc
high,vhigh,5more,4,med,low,unacc
high,vhigh,5more,4,med,med,unacc
high,vhigh,5more,4,med,high,unacc
high,vhigh,5more,4,big,low,unacc
high,vhigh,5more,4,big,med,unacc
high,vhigh,5more,4,big,high,unacc
high,vhigh,5more,more,small,low,unacc
high,vhigh,5more,more,small,med,unacc
high,vhigh,5more,more,small,high,unacc
high,vhigh,5more,more,med,low,unacc
high,vhigh,5more,more,med,med,unacc
high,vhigh,5more,more,med,high,unacc
high,vhigh,5more,more,big,low,unacc
high,vhigh,5more,more,big,med,unacc
high,vhigh,5more,more,big,high,unacc
high,high,2,2,small,low,unacc
high,high,2,2,small,med,unacc
high,high,2,2,small,high,unacc
high,high,2,2,med,low,unacc
high,high,2,2,med,med,unacc
high,high,2,2,med,high,unacc
high,high,2,2,big,low,unacc
high,high,2,2,big,med,unacc
high,high,2,2,big,high,unacc
high,high,2,4,small,low,unacc
high,high,2,4,small,med,unacc
high,high,2,4,small,high,acc
high,high,2,4,med,low,unacc
high,high,2,4,med,med,unacc
high,high,2,4,med,high,acc
high,high,2,4,big,low,unacc
high,high,2,4,big,med,acc
high,high,2,4,big,high,acc
high,high,2,more,small,low,unacc
high,high,2,more,small,med,unacc
high,high,2,more,small,high,unacc
high,high,2,more,med,low,unacc
high,high,2,more,med,med,unacc
high,high,2,more,med,high,acc
high,high,2,more,big,low,unacc
high,high,2,more,big,med,acc
high,high,2,more,big,high,acc
high,high,3,2,small,low,unacc
high,high,3,2,small,med,unacc
high,high,3,2,small,high,unacc
high,high,3,2,med,low,unacc
high,high,3,2,med,med,unacc
high,high,3,2,med,high,unacc
high,high,3,2,big,low,unacc
high,high,3,2,big,med,unacc
high,high,3,2,big,high,unacc
high,high,3,4,small,low,unacc
high,high,3,4,small,med,unacc
high,high,3,4,small,high,acc
high,high,3,4,med,low,unacc
high,high,3,4,med,med,unacc
high,high,3,4,med,high,acc
high,high,3,4,big,low,unacc
high,high,3,4,big,med,acc
high,high,3,4,big,high,acc
high,high,3,more,small,low,unacc
high,high,3,more,small,med,unacc
high,high,3,more,small,high,acc
high,high,3,more,med,low,unacc
high,high,3,more,med,med,acc
high,high,3,more,med,high,acc
high,high,3,more,big,low,unacc
high,high,3,more,big,med,acc
high,high,3,more,big,high,acc
high,high,4,2,small,low,unacc
high,high,4,2,small,med,unacc
high,high,4,2,small,high,unacc
high,high,4,2,med,low,unacc
high,high,4,2,med,med,unacc
high,high,4,2,med,high,unacc
high,high,4,2,big,low,unacc
high,high,4,2,big,med,unacc
high,high,4,2,big,high,unacc
high,high,4,4,small,low,unacc
high,high,4,4,small,med,unacc
high,high,4,4,small,high,acc
high,high,4,4,med,low,unacc
high,high,4,4,med,med,acc
high,high,4,4,med,high,acc
high,high,4,4,big,low,unacc
high,high,4,4,big,med,acc
high,high,4,4,big,high,acc
high,high,4,more,small,low,unacc
high,high,4,more,small,med,unacc
high,high,4,more,small,high,acc
high,high,4,more,med,low,unacc
high,high,4,more,med,med,acc
high,high,4,more,med,high,acc
high,high,4,more,big,low,unacc
high,high,4,more,big,med,acc
high,high,4,more,big,high,acc
high,high,5more,2,small,low,unacc
high,high,5more,2,small,med,unacc
high,high,5more,2,small,high,unacc
high,high,5more,2,med,low,unacc
high,high,5more,2,med,med,unacc
high,high,5more,2,med,high,unacc
high,high,5more,2,big,low,unacc
high,high,5more,2,big,med,unacc
high,high,5more,2,big,high,unacc
high,high,5more,4,small,low,unacc
high,high,5more,4,small,med,unacc
high,high,5more,4,small,high,acc
high,high,5more,4,med,low,unacc
high,high,5more,4,med,med,acc
high,high,5more,4,med,high,acc
high,high,5more,4,big,low,unacc
high,high,5more,4,big,med,acc
high,high,5more,4,big,high,acc
high,high,5more,more,small,low,unacc
high,high,5more,more,small,med,unacc
high,high,5more,more,small,high,acc
high,high,5more,more,med,low,unacc
high,high,5more,more,med,med,acc
high,high,5more,more,med,high,acc
high,high,5more,more,big,low,unacc
high,high,5more,more,big,med,acc
high,high,5more,more,big,high,acc
high,med,2,2,small,low,unacc
high,med,2,2,small,med,unacc
high,med,2,2,small,high,unacc
high,med,2,2,med,low,unacc
high,med,2,2,med,med,unacc
high,med,2,2,med,high,unacc
high,med,2,2,big,low,unacc
high,med,2,2,big,med,unacc
high,med,2,2,big,high,unacc
high,med,2,4,small,low,unacc
high,med,2,4,small,med,unacc
high,med,2,4,small,high,acc
high,med,2,4,med,low,unacc
high,med,2,4,med,med,unacc
high,med,2,4,med,high,acc
high,med,2,4,big,low,unacc
high,med,2,4,big,med,acc
high,med,2,4,big,high,acc
high,med,2,more,small,low,unacc
high,med,2,more,small,med,unacc
high,med,2,more,small,high,unacc
high,med,2,more,med,low,unacc
high,med,2,more,med,med,unacc
high,med,2,more,med,high,acc
high,med,2,more,big,low,unacc
high,med,2,more,big,med,acc
high,med,2,more,big,high,acc
high,med,3,2,small,low,unacc
high,med,3,2,small,med,unacc
high,med,3,2,small,high,unacc
high,med,3,2,med,low,unacc
high,med,3,2,med,med,unacc
high,med,3,2,med,high,unacc
high,med,3,2,big,low,unacc
high,med,3,2,big,med,unacc
high,med,3,2,big,high,unacc
high,med,3,4,small,low,unacc
high,med,3,4,small,med,unacc
high,med,3,4,small,high,acc
high,med,3,4,med,low,unacc
high,med,3,4,med,med,unacc
high,med,3,4,med,high,acc
high,med,3,4,big,low,unacc
high,med,3,4,big,med,acc
high,med,3,4,big,high,acc
high,med,3,more,small,low,unacc
high,med,3,more,small,med,unacc
high,med,3,more,small,high,acc
high,med,3,more,med,low,unacc
high,med,3,more,med,med,acc
high,med,3,more,med,high,acc
high,med,3,more,big,low,unacc
high,med,3,more,big,med,acc
high,med,3,more,big,high,acc
high,med,4,2,small,low,unacc
high,med,4,2,small,med,unacc
high,med,4,2,small,high,unacc
high,med,4,2,med,low,unacc
high,med,4,2,med,med,unacc
high,med,4,2,med,high,unacc
high,med,4,2,big,low,unacc
high,med,4,2,big,med,unacc
high,med,4,2,big,high,unacc
high,med,4,4,small,low,unacc
high,med,4,4,small,med,unacc
high,med,4,4,small,high,acc
high,med,4,4,med,low,unacc
high,med,4,4,med,med,acc
high,med,4,4,med,high,acc
high,med,4,4,big,low,unacc
high,med,4,4,big,med,acc
high,med,4,4,big,high,acc
high,med,4,more,small,low,unacc
high,med,4,more,small,med,unacc
high,med,4,more,small,high,acc
high,med,4,more,med,low,unacc
high,med,4,more,med,med,acc
high,med,4,more,med,high,acc
high,med,4,more,big,low,unacc
high,med,4,more,big,med,acc
high,med,4,more,big,high,acc
high,med,5more,2,small,low,unacc
high,med,5more,2,small,med,unacc
high,med,5more,2,small,high,unacc
high,med,5more,2,med,low,unacc
high,med,5more,2,med,med,unacc
high,med,5more,2,med,high,unacc
high,med,5more,2,big,low,unacc
high,med,5more,2,big,med,unacc
high,med,5more,2,big,high,unacc
high,med,5more,4,small,low,unacc
high,med,5more,4,small,med,unacc
high,med,5more,4,small,high,acc
high,med,5more,4,med,low,unacc
high,med,5more,4,med,med,acc
high,med,5more,4,med,high,acc
high,med,5more,4,big,low,unacc
high,med,5more,4,big,med,acc
high,med,5more,4,big,high,acc
high,med,5more,more,small,low,unacc
high,med,5more,more,small,med,unacc
high,med,5more,more,small,high,acc
high,med,5more,more,med,low,unacc
high,med,5more,more,med,med,acc
high,med,5more,more,med,high,acc
high,med,5more,more,big,low,unacc
high,med,5more,more,big,med,acc
high,med,5more,more,big,high,acc
high,low,2,2,small,low,unacc
high,low,2,2,small,med,unacc
high,low,2,2,small,high,unacc
high,low,2,2,med,low,unacc
high,low,2,2,med,med,unacc
high,low,2,2,med,high,unacc
high,low,2,2,big,low,unacc
high,low,2,2,big,med,unacc
high,low,2,2,big,high,unacc
high,low,2,4,small,low,unacc
high,low,2,4,small,med,unacc
high,low,2,4,small,high,acc
high,low,2,4,med,low,unacc
high,low,2,4,med,med,unacc
high,low,2,4,med,high,acc
high,low,2,4,big,low,unacc
high,low,2,4,big,med,acc
high,low,2,4,big,high,acc
high,low,2,more,small,low,unacc
high,low,2,more,small,med,unacc
high,low,2,more,small,high,unacc
high,low,2,more,med,low,unacc
high,low,2,more,med,med,unacc
high,low,2,more,med,high,acc
high,low,2,more,big,low,unacc
high,low,2,more,big,med,acc
high,low,2,more,big,high,acc
high,low,3,2,small,low,unacc
high,low,3,2,small,med,unacc
high,low,3,2,small,high,unacc
high,low,3,2,med,low,unacc
high,low,3,2,med,med,unacc
high,low,3,2,med,high,unacc
high,low,3,2,big,low,unacc
high,low,3,2,big,med,unacc
high,low,3,2,big,high,unacc
high,low,3,4,small,low,unacc
high,low,3,4,small,med,unacc
high,low,3,4,small,high,acc
high,low,3,4,med,low,unacc
high,low,3,4,med,med,unacc
high,low,3,4,med,high,acc
high,low,3,4,big,low,unacc
high,low,3,4,big,med,acc
high,low,3,4,big,high,acc
high,low,3,more,small,low,unacc
high,low,3,more,small,med,unacc
high,low,3,more,small,high,acc
high,low,3,more,med,low,unacc
high,low,3,more,med,med,acc
high,low,3,more,med,high,acc
high,low,3,more,big,low,unacc
high,low,3,more,big,med,acc
high,low,3,more,big,high,acc
high,low,4,2,small,low,unacc
high,low,4,2,small,med,unacc
high,low,4,2,small,high,unacc
high,low,4,2,med,low,unacc
high,low,4,2,med,med,unacc
high,low,4,2,med,high,unacc
high,low,4,2,big,low,unacc
high,low,4,2,big,med,unacc
high,low,4,2,big,high,unacc
high,low,4,4,small,low,unacc
high,low,4,4,small,med,unacc
high,low,4,4,small,high,acc
high,low,4,4,med,low,unacc
high,low,4,4,med,med,acc
high,low,4,4,med,high,acc
high,low,4,4,big,low,unacc
high,low,4,4,big,med,acc
high,low,4,4,big,high,acc
high,low,4,more,small,low,unacc
high,low,4,more,small,med,unacc
high,low,4,more,small,high,acc
high,low,4,more,med,low,unacc
high,low,4,more,med,med,acc
high,low,4,more,med,high,acc
high,low,4,more,big,low,unacc
high,low,4,more,big,med,acc
high,low,4,more,big,high,acc
high,low,5more,2,small,low,unacc
high,low,5more,2,small,med,unacc
high,low,5more,2,small,high,unacc
high,low,5more,2,med,low,unacc
high,low,5more,2,med,med,unacc
high,low,5more,2,med,high,unacc
high,low,5more,2,big,low,unacc
high,low,5more,2,big,med,unacc
high,low,5more,2,big,high,unacc
high,low,5more,4,small,low,unacc
high,low,5more,4,small,med,unacc
high,low,5more,4,small,high,acc
high,low,5more,4,med,low,unacc
high,low,5more,4,med,med,acc
high,low,5more,4,med,high,acc
high,low,5more,4,big,low,unacc
high,low,5more,4,big,med,acc
high,low,5more,4,big,high,acc
high,low,5more,more,small,low,unacc
high,low,5more,more,small,med,unacc
high,low,5more,more,small,high,acc
high,low,5more,more,med,low,unacc
high,low,5more,more,med,med,acc
high,low,5more,more,med,high,acc
high,low,5more,more,big,low,unacc
high,low,5more,more,big,med,acc
high,low,5more,more,big,high,acc
med,vhigh,2,2,small,low,unacc
med,vhigh,2,2,small,med,unacc
med,vhigh,2,2,small,high,unacc
med,vhigh,2,2,med,low,unacc
med,vhigh,2,2,med,med,unacc
med,vhigh,2,2,med,high,unacc
med,vhigh,2,2,big,low,unacc
med,vhigh,2,2,big,med,unacc
med,vhigh,2,2,big,high,unacc
med,vhigh,2,4,small,low,unacc
med,vhigh,2,4,small,med,unacc
med,vhigh,2,4,small,high,acc
med,vhigh,2,4,med,low,unacc
med,vhigh,2,4,med,med,unacc
med,vhigh,2,4,med,high,acc
med,vhigh,2,4,big,low,unacc
med,vhigh,2,4,big,med,acc
med,vhigh,2,4,big,high,acc
med,vhigh,2,more,small,low,unacc
med,vhigh,2,more,small,med,unacc
med,vhigh,2,more,small,high,unacc
med,vhigh,2,more,med,low,unacc
med,vhigh,2,more,med,med,unacc
med,vhigh,2,more,med,high,acc
med,vhigh,2,more,big,low,unacc
med,vhigh,2,more,big,med,acc
med,vhigh,2,more,big,high,acc
med,vhigh,3,2,small,low,unacc
med,vhigh,3,2,small,med,unacc
med,vhigh,3,2,small,high,unacc
med,vhigh,3,2,med,low,unacc
med,vhigh,3,2,med,med,unacc
med,vhigh,3,2,med,high,unacc
med,vhigh,3,2,big,low,unacc
med,vhigh,3,2,big,med,unacc
med,vhigh,3,2,big,high,unacc
med,vhigh,3,4,small,low,unacc
med,vhigh,3,4,small,med,unacc
med,vhigh,3,4,small,high,acc
med,vhigh,3,4,med,low,unacc
med,vhigh,3,4,med,med,unacc
med,vhigh,3,4,med,high,acc
med,vhigh,3,4,big,low,unacc
med,vhigh,3,4,big,med,acc
med,vhigh,3,4,big,high,acc
med,vhigh,3,more,small,low,unacc
med,vhigh,3,more,small,med,unacc
med,vhigh,3,more,small,high,acc
med,vhigh,3,more,med,low,unacc
med,vhigh,3,more,med,med,acc
med,vhigh,3,more,med,high,acc
med,vhigh,3,more,big,low,unacc
med,vhigh,3,more,big,med,acc
med,vhigh,3,more,big,high,acc
med,vhigh,4,2,small,low,unacc
med,vhigh,4,2,small,med,unacc
med,vhigh,4,2,small,high,unacc
med,vhigh,4,2,med,low,unacc
med,vhigh,4,2,med,med,unacc
med,vhigh,4,2,med,high,unacc
med,vhigh,4,2,big,low,unacc
med,vhigh,4,2,big,med,unacc
med,vhigh,4,2,big,high,unacc
med,vhigh,4,4,small,low,unacc
med,vhigh,4,4,small,med,unacc
med,vhigh,4,4,small,high,acc
med,vhigh,4,4,med,low,unacc
med,vhigh,4,4,med,med,acc
med,vhigh,4,4,med,high,acc
med,vhigh,4,4,big,low,unacc
med,vhigh,4,4,big,med,acc
med,vhigh,4,4,big,high,acc
med,vhigh,4,more,small,low,unacc
med,vhigh,4,more,small,med,unacc
med,vhigh,4,more,small,high,acc
med,vhigh,4,more,med,low,unacc
med,vhigh,4,more,med,med,acc
med,vhigh,4,more,med,high,acc
med,vhigh,4,more,big,low,unacc
med,vhigh,4,more,big,med,acc
med,vhigh,4,more,big,high,acc
med,vhigh,5more,2,small,low,unacc
med,vhigh,5more,2,small,med,unacc
med,vhigh,5more,2,small,high,unacc
med,vhigh,5more,2,med,low,unacc
med,vhigh,5more,2,med,med,unacc
med,vhigh,5more,2,med,high,unacc
med,vhigh,5more,2,big,low,unacc
med,vhigh,5more,2,big,med,unacc
med,vhigh,5more,2,big,high,unacc
med,vhigh,5more,4,small,low,unacc
med,vhigh,5more,4,small,med,unacc
med,vhigh,5more,4,small,high,acc
med,vhigh,5more,4,med,low,unacc
med,vhigh,5more,4,med,med,acc
med,vhigh,5more,4,med,high,acc
med,vhigh,5more,4,big,low,unacc
med,vhigh,5more,4,big,med,acc
med,vhigh,5more,4,big,high,acc
med,vhigh,5more,more,small,low,unacc
med,vhigh,5more,more,small,med,unacc
med,vhigh,5more,more,small,high,acc
med,vhigh,5more,more,med,low,unacc
med,vhigh,5more,more,med,med,acc
med,vhigh,5more,more,med,high,acc
med,vhigh,5more,more,big,low,unacc
med,vhigh,5more,more,big,med,acc
med,vhigh,5more,more,big,high,acc
med,high,2,2,small,low,unacc
med,high,2,2,small,med,unacc
med,high,2,2,small,high,unacc
med,high,2,2,med,low,unacc
med,high,2,2,med,med,unacc
med,high,2,2,med,high,unacc
med,high,2,2,big,low,unacc
med,high,2,2,big,med,unacc
med,high,2,2,big,high,unacc
med,high,2,4,small,low,unacc
med,high,2,4,small,med,unacc
med,high,2,4,small,high,acc
med,high,2,4,med,low,unacc
med,high,2,4,med,med,unacc
med,high,2,4,med,high,acc
med,high,2,4,big,low,unacc
med,high,2,4,big,med,acc
med,high,2,4,big,high,acc
med,high,2,more,small,low,unacc
med,high,2,more,small,med,unacc
med,high,2,more,small,high,unacc
med,high,2,more,med,low,unacc
med,high,2,more,med,med,unacc
med,high,2,more,med,high,acc
med,high,2,more,big,low,unacc
med,high,2,more,big,med,acc
med,high,2,more,big,high,acc
med,high,3,2,small,low,unacc
med,high,3,2,small,med,unacc
med,high,3,2,small,high,unacc
med,high,3,2,med,low,unacc
med,high,3,2,med,med,unacc
med,high,3,2,med,high,unacc
med,high,3,2,big,low,unacc
med,high,3,2,big,med,unacc
med,high,3,2,big,high,unacc
med,high,3,4,small,low,unacc
med,high,3,4,small,med,unacc
med,high,3,4,small,high,acc
med,high,3,4,med,low,unacc
med,high,3,4,med,med,unacc
med,high,3,4,med,high,acc
med,high,3,4,big,low,unacc
med,high,3,4,big,med,acc
med,high,3,4,big,high,acc
med,high,3,more,small,low,unacc
med,high,3,more,small,med,unacc
med,high,3,more,small,high,acc
med,high,3,more,med,low,unacc
med,high,3,more,med,med,acc
med,high,3,more,med,high,acc
med,high,3,more,big,low,unacc
med,high,3,more,big,med,acc
med,high,3,more,big,high,acc
med,high,4,2,small,low,unacc
med,high,4,2,small,med,unacc
med,high,4,2,small,high,unacc
med,high,4,2,med,low,unacc
med,high,4,2,med,med,unacc
med,high,4,2,med,high,unacc
med,high,4,2,big,low,unacc
med,high,4,2,big,med,unacc
med,high,4,2,big,high,unacc
med,high,4,4,small,low,unacc
med,high,4,4,small,med,unacc
med,high,4,4,small,high,acc
med,high,4,4,med,low,unacc
med,high,4,4,med,med,acc
med,high,4,4,med,high,acc
med,high,4,4,big,low,unacc
med,high,4,4,big,med,acc
med,high,4,4,big,high,acc
med,high,4,more,small,low,unacc
med,high,4,more,small,med,unacc
med,high,4,more,small,high,acc
med,high,4,more,med,low,unacc
med,high,4,more,med,med,acc
med,high,4,more,med,high,acc
med,high,4,more,big,low,unacc
med,high,4,more,big,med,acc
med,high,4,more,big,high,acc
med,high,5more,2,small,low,unacc
med,high,5more,2,small,med,unacc
med,high,5more,2,small,high,unacc
med,high,5more,2,med,low,unacc
med,high,5more,2,med,med,unacc
med,high,5more,2,med,high,unacc
med,high,5more,2,big,low,unacc
med,high,5more,2,big,med,unacc
med,high,5more,2,big,high,unacc
med,high,5more,4,small,low,unacc
med,high,5more,4,small,med,unacc
med,high,5more,4,small,high,acc
med,high,5more,4,med,low,unacc
med,high,5more,4,med,med,acc
med,high,5more,4,med,high,acc
med,high,5more,4,big,low,unacc
med,high,5more,4,big,med,acc
med,high,5more,4,big,high,acc
med,high,5more,more,small,low,unacc
med,high,5more,more,small,med,unacc
med,high,5more,more,small,high,acc
med,high,5more,more,med,low,unacc
med,high,5more,more,med,med,acc
med,high,5more,more,med,high,acc
med,high,5more,more,big,low,unacc
med,high,5more,more,big,med,acc
med,high,5more,more,big,high,acc
med,med,2,2,small,low,unacc
med,med,2,2,small,med,unacc
med,med,2,2,small,high,unacc
med,med,2,2,med,low,unacc
med,med,2,2,med,med,unacc
med,med,2,2,med,high,unacc
med,med,2,2,big,low,unacc
med,med,2,2,big,med,unacc
med,med,2,2,big,high,unacc
med,med,2,4,small,low,unacc
med,med,2,4,small,med,acc
med,med,2,4,small,high,acc
med,med,2,4,med,low,unacc
med,med,2,4,med,med,acc
med,med,2,4,med,high,acc
med,med,2,4,big,low,unacc
med,med,2,4,big,med,acc
med,med,2,4,big,high,vgood
med,med,2,more,small,low,unacc
med,med,2,more,small,med,unacc
med,med,2,more,small,high,unacc
med,med,2,more,med,low,unacc
med,med,2,more,med,med,acc
med,med,2,more,med,high,acc
med,med,2,more,big,low,unacc
med,med,2,more,big,med,acc
med,med,2,more,big,high,vgood
med,med,3,2,small,low,unacc
med,med,3,2,small,med,unacc
med,med,3,2,small,high,unacc
med,med,3,2,med,low,unacc
med,med,3,2,med,med,unacc
med,med,3,2,med,high,unacc
med,med,3,2,big,low,unacc
med,med,3,2,big,med,unacc
med,med,3,2,big,high,unacc
med,med,3,4,small,low,unacc
med,med,3,4,small,med,acc
med,med,3,4,small,high,acc
med,med,3,4,med,low,unacc
med,med,3,4,med,med,acc
med,med,3,4,med,high,acc
med,med,3,4,big,low,unacc
med,med,3,4,big,med,acc
med,med,3,4,big,high,vgood
med,med,3,more,small,low,unacc
med,med,3,more,small,med,acc
med,med,3,more,small,high,acc
med,med,3,more,med,low,unacc
med,med,3,more,med,med,acc
med,med,3,more,med,high,vgood
med,med,3,more,big,low,unacc
med,med,3,more,big,med,acc
med,med,3,more,big,high,vgood
med,med,4,2,small,low,unacc
med,med,4,2,small,med,unacc
med,med,4,2,small,high,unacc
med,med,4,2,med,low,unacc
med,med,4,2,med,med,unacc
med,med,4,2,med,high,unacc
med,med,4,2,big,low,unacc
med,med,4,2,big,med,unacc
med,med,4,2,big,high,unacc
med,med,4,4,small,low,unacc
med,med,4,4,small,med,acc
med,med,4,4,small,high,acc
med,med,4,4,med,low,unacc
med,med,4,4,med,med,acc
med,med,4,4,med,high,vgood
med,med,4,4,big,low,unacc
med,med,4,4,big,med,acc
med,med,4,4,big,high,vgood
med,med,4,more,small,low,unacc
med,med,4,more,small,med,acc
med,med,4,more,small,high,acc
med,med,4,more,med,low,unacc
med,med,4,more,med,med,acc
med,med,4,more,med,high,vgood
med,med,4,more,big,low,unacc
med,med,4,more,big,med,acc
med,med,4,more,big,high,vgood
med,med,5more,2,small,low,unacc
med,med,5more,2,small,med,unacc
med,med,5more,2,small,high,unacc
med,med,5more,2,med,low,unacc
med,med,5more,2,med,med,unacc
med,med,5more,2,med,high,unacc
med,med,5more,2,big,low,unacc
med,med,5more,2,big,med,unacc
med,med,5more,2,big,high,unacc
med,med,5more,4,small,low,unacc
med,med,5more,4,small,med,acc
med,med,5more,4,small,high,acc
med,med,5more,4,med,low,unacc
med,med,5more,4,med,med,acc
med,med,5more,4,med,high,vgood
med,med,5more,4,big,low,unacc
med,med,5more,4,big,med,acc
med,med,5more,4,big,high,vgood
med,med,5more,more,small,low,unacc
med,med,5more,more,small,med,acc
med,med,5more,more,small,high,acc
med,med,5more,more,med,low,unacc
med,med,5more,more,med,med,acc
med,med,5more,more,med,high,vgood
med,med,5more,more,big,low,unacc
med,med,5more,more,big,med,acc
med,med,5more,more,big,high,vgood
med,low,2,2,small,low,unacc
med,low,2,2,small,med,unacc
med,low,2,2,small,high,unacc
med,low,2,2,med,low,unacc
med,low,2,2,med,med,unacc
med,low,2,2,med,high,unacc
med,low,2,2,big,low,unacc
med,low,2,2,big,med,unacc
med,low,2,2,big,high,unacc
med,low,2,4,small,low,unacc
med,low,2,4,small,med,acc
med,low,2,4,small,high,good
med,low,2,4,med,low,unacc
med,low,2,4,med,med,acc
med,low,2,4,med,high,good
med,low,2,4,big,low,unacc
med,low,2,4,big,med,good
med,low,2,4,big,high,vgood
med,low,2,more,small,low,unacc
med,low,2,more,small,med,unacc
med,low,2,more,small,high,unacc
med,low,2,more,med,low,unacc
med,low,2,more,med,med,acc
med,low,2,more,med,high,good
med,low,2,more,big,low,unacc
med,low,2,more,big,med,good
med,low,2,more,big,high,vgood
med,low,3,2,small,low,unacc
med,low,3,2,small,med,unacc
med,low,3,2,small,high,unacc
med,low,3,2,med,low,unacc
med,low,3,2,med,med,unacc
med,low,3,2,med,high,unacc
med,low,3,2,big,low,unacc
med,low,3,2,big,med,unacc
med,low,3,2,big,high,unacc
med,low,3,4,small,low,unacc
med,low,3,4,small,med,acc
med,low,3,4,small,high,good
med,low,3,4,med,low,unacc
med,low,3,4,med,med,acc
med,low,3,4,med,high,good
med,low,3,4,big,low,unacc
med,low,3,4,big,med,good
med,low,3,4,big,high,vgood
med,low,3,more,small,low,unacc
med,low,3,more,small,med,acc
med,low,3,more,small,high,good
med,low,3,more,med,low,unacc
med,low,3,more,med,med,good
med,low,3,more,med,high,vgood
med,low,3,more,big,low,unacc
med,low,3,more,big,med,good
med,low,3,more,big,high,vgood
med,low,4,2,small,low,unacc
med,low,4,2,small,med,unacc
med,low,4,2,small,high,unacc
med,low,4,2,med,low,unacc
med,low,4,2,med,med,unacc
med,low,4,2,med,high,unacc
med,low,4,2,big,low,unacc
med,low,4,2,big,med,unacc
med,low,4,2,big,high,unacc
med,low,4,4,small,low,unacc
med,low,4,4,small,med,acc
med,low,4,4,small,high,good
med,low,4,4,med,low,unacc
med,low,4,4,med,med,good
med,low,4,4,med,high,vgood
med,low,4,4,big,low,unacc
med,low,4,4,big,med,good
med,low,4,4,big,high,vgood
med,low,4,more,small,low,unacc
med,low,4,more,small,med,acc
med,low,4,more,small,high,good
med,low,4,more,med,low,unacc
med,low,4,more,med,med,good
med,low,4,more,med,high,vgood
med,low,4,more,big,low,unacc
med,low,4,more,big,med,good
med,low,4,more,big,high,vgood
med,low,5more,2,small,low,unacc
med,low,5more,2,small,med,unacc
med,low,5more,2,small,high,unacc
med,low,5more,2,med,low,unacc
med,low,5more,2,med,med,unacc
med,low,5more,2,med,high,unacc
med,low,5more,2,big,low,unacc
med,low,5more,2,big,med,unacc
med,low,5more,2,big,high,unacc
med,low,5more,4,small,low,unacc
med,low,5more,4,small,med,acc
med,low,5more,4,small,high,good
med,low,5more,4,med,low,unacc
med,low,5more,4,med,med,good
med,low,5more,4,med,high,vgood
med,low,5more,4,big,low,unacc
med,low,5more,4,big,med,good
med,low,5more,4,big,high,vgood
med,low,5more,more,small,low,unacc
med,low,5more,more,small,med,acc
med,low,5more,more,small,high,good
med,low,5more,more,med,low,unacc
med,low,5more,more,med,med,good
med,low,5more,more,med,high,vgood
med,low,5more,more,big,low,unacc
med,low,5more,more,big,med,good
med,low,5more,more,big,high,vgood
low,vhigh,2,2,small,low,unacc
low,vhigh,2,2,small,med,unacc
low,vhigh,2,2,small,high,unacc
low,vhigh,2,2,med,low,unacc
low,vhigh,2,2,med,med,unacc
low,vhigh,2,2,med,high,unacc
low,vhigh,2,2,big,low,unacc
low,vhigh,2,2,big,med,unacc
low,vhigh,2,2,big,high,unacc
low,vhigh,2,4,small,low,unacc
low,vhigh,2,4,small,med,unacc
low,vhigh,2,4,small,high,acc
low,vhigh,2,4,med,low,unacc
low,vhigh,2,4,med,med,unacc
low,vhigh,2,4,med,high,acc
low,vhigh,2,4,big,low,unacc
low,vhigh,2,4,big,med,acc
low,vhigh,2,4,big,high,acc
low,vhigh,2,more,small,low,unacc
low,vhigh,2,more,small,med,unacc
low,vhigh,2,more,small,high,unacc
low,vhigh,2,more,med,low,unacc
low,vhigh,2,more,med,med,unacc
low,vhigh,2,more,med,high,acc
low,vhigh,2,more,big,low,unacc
low,vhigh,2,more,big,med,acc
low,vhigh,2,more,big,high,acc
low,vhigh,3,2,small,low,unacc
low,vhigh,3,2,small,med,unacc
low,vhigh,3,2,small,high,unacc
low,vhigh,3,2,med,low,unacc
low,vhigh,3,2,med,med,unacc
low,vhigh,3,2,med,high,unacc
low,vhigh,3,2,big,low,unacc
low,vhigh,3,2,big,med,unacc
low,vhigh,3,2,big,high,unacc
low,vhigh,3,4,small,low,unacc
low,vhigh,3,4,small,med,unacc
low,vhigh,3,4,small,high,acc
low,vhigh,3,4,med,low,unacc
low,vhigh,3,4,med,med,unacc
low,vhigh,3,4,med,high,acc
low,vhigh,3,4,big,low,unacc
low,vhigh,3,4,big,med,acc
low,vhigh,3,4,big,high,acc
low,vhigh,3,more,small,low,unacc
low,vhigh,3,more,small,med,unacc
low,vhigh,3,more,small,high,acc
low,vhigh,3,more,med,low,unacc
low,vhigh,3,more,med,med,acc
low,vhigh,3,more,med,high,acc
low,vhigh,3,more,big,low,unacc
low,vhigh,3,more,big,med,acc
low,vhigh,3,more,big,high,acc
low,vhigh,4,2,small,low,unacc
low,vhigh,4,2,small,med,unacc
low,vhigh,4,2,small,high,unacc
low,vhigh,4,2,med,low,unacc
low,vhigh,4,2,med,med,unacc
low,vhigh,4,2,med,high,unacc
low,vhigh,4,2,big,low,unacc
low,vhigh,4,2,big,med,unacc
low,vhigh,4,2,big,high,unacc
low,vhigh,4,4,small,low,unacc
low,vhigh,4,4,small,med,unacc
low,vhigh,4,4,small,high,acc
low,vhigh,4,4,med,low,unacc
low,vhigh,4,4,med,med,acc
low,vhigh,4,4,med,high,acc
low,vhigh,4,4,big,low,unacc
low,vhigh,4,4,big,med,acc
low,vhigh,4,4,big,high,acc
low,vhigh,4,more,small,low,unacc
low,vhigh,4,more,small,med,unacc
low,vhigh,4,more,small,high,acc
low,vhigh,4,more,med,low,unacc
low,vhigh,4,more,med,med,acc
low,vhigh,4,more,med,high,acc
low,vhigh,4,more,big,low,unacc
low,vhigh,4,more,big,med,acc
low,vhigh,4,more,big,high,acc
low,vhigh,5more,2,small,low,unacc
low,vhigh,5more,2,small,med,unacc
low,vhigh,5more,2,small,high,unacc
low,vhigh,5more,2,med,low,unacc
low,vhigh,5more,2,med,med,unacc
low,vhigh,5more,2,med,high,unacc
low,vhigh,5more,2,big,low,unacc
low,vhigh,5more,2,big,med,unacc
low,vhigh,5more,2,big,high,unacc
low,vhigh,5more,4,small,low,unacc
low,vhigh,5more,4,small,med,unacc
low,vhigh,5more,4,small,high,acc
low,vhigh,5more,4,med,low,unacc
low,vhigh,5more,4,med,med,acc
low,vhigh,5more,4,med,high,acc
low,vhigh,5more,4,big,low,unacc
low,vhigh,5more,4,big,med,acc
low,vhigh,5more,4,big,high,acc
low,vhigh,5more,more,small,low,unacc
low,vhigh,5more,more,small,med,unacc
low,vhigh,5more,more,small,high,acc
low,vhigh,5more,more,med,low,unacc
low,vhigh,5more,more,med,med,acc
low,vhigh,5more,more,med,high,acc
low,vhigh,5more,more,big,low,unacc
low,vhigh,5more,more,big,med,acc
low,vhigh,5more,more,big,high,acc
low,high,2,2,small,low,unacc
low,high,2,2,small,med,unacc
low,high,2,2,small,high,unacc
low,high,2,2,med,low,unacc
low,high,2,2,med,med,unacc
low,high,2,2,med,high,unacc
low,high,2,2,big,low,unacc
low,high,2,2,big,med,unacc
low,high,2,2,big,high,unacc
low,high,2,4,small,low,unacc
low,high,2,4,small,med,acc
low,high,2,4,small,high,acc
low,high,2,4,med,low,unacc
low,high,2,4,med,med,acc
low,high,2,4,med,high,acc
low,high,2,4,big,low,unacc
low,high,2,4,big,med,acc
low,high,2,4,big,high,vgood
low,high,2,more,small,low,unacc
low,high,2,more,small,med,unacc
low,high,2,more,small,high,unacc
low,high,2,more,med,low,unacc
low,high,2,more,med,med,acc
low,high,2,more,med,high,acc
low,high,2,more,big,low,unacc
low,high,2,more,big,med,acc
low,high,2,more,big,high,vgood
low,high,3,2,small,low,unacc
low,high,3,2,small,med,unacc
low,high,3,2,small,high,unacc
low,high,3,2,med,low,unacc
low,high,3,2,med,med,unacc
low,high,3,2,med,high,unacc
low,high,3,2,big,low,unacc
low,high,3,2,big,med,unacc
low,high,3,2,big,high,unacc
low,high,3,4,small,low,unacc
low,high,3,4,small,med,acc
low,high,3,4,small,high,acc
low,high,3,4,med,low,unacc
low,high,3,4,med,med,acc
low,high,3,4,med,high,acc
low,high,3,4,big,low,unacc
low,high,3,4,big,med,acc
low,high,3,4,big,high,vgood
low,high,3,more,small,low,unacc
low,high,3,more,small,med,acc
low,high,3,more,small,high,acc
low,high,3,more,med,low,unacc
low,high,3,more,med,med,acc
low,high,3,more,med,high,vgood
low,high,3,more,big,low,unacc
low,high,3,more,big,med,acc
low,high,3,more,big,high,vgood
low,high,4,2,small,low,unacc
low,high,4,2,small,med,unacc
low,high,4,2,small,high,unacc
low,high,4,2,med,low,unacc
low,high,4,2,med,med,unacc
low,high,4,2,med,high,unacc
low,high,4,2,big,low,unacc
low,high,4,2,big,med,unacc
low,high,4,2,big,high,unacc
low,high,4,4,small,low,unacc
low,high,4,4,small,med,acc
low,high,4,4,small,high,acc
low,high,4,4,med,low,unacc
low,high,4,4,med,med,acc
low,high,4,4,med,high,vgood
low,high,4,4,big,low,unacc
low,high,4,4,big,med,acc
low,high,4,4,big,high,vgood
low,high,4,more,small,low,unacc
low,high,4,more,small,med,acc
low,high,4,more,small,high,acc
low,high,4,more,med,low,unacc
low,high,4,more,med,med,acc
low,high,4,more,med,high,vgood
low,high,4,more,big,low,unacc
low,high,4,more,big,med,acc
low,high,4,more,big,high,vgood
low,high,5more,2,small,low,unacc
low,high,5more,2,small,med,unacc
low,high,5more,2,small,high,unacc
low,high,5more,2,med,low,unacc
low,high,5more,2,med,med,unacc
low,high,5more,2,med,high,unacc
low,high,5more,2,big,low,unacc
low,high,5more,2,big,med,unacc
low,high,5more,2,big,high,unacc
low,high,5more,4,small,low,unacc
low,high,5more,4,small,med,acc
low,high,5more,4,small,high,acc
low,high,5more,4,med,low,unacc
low,high,5more,4,med,med,acc
low,high,5more,4,med,high,vgood
low,high,5more,4,big,low,unacc
low,high,5more,4,big,med,acc
low,high,5more,4,big,high,vgood
low,high,5more,more,small,low,unacc
low,high,5more,more,small,med,acc
low,high,5more,more,small,high,acc
low,high,5more,more,med,low,unacc
low,high,5more,more,med,med,acc
low,high,5more,more,med,high,vgood
low,high,5more,more,big,low,unacc
low,high,5more,more,big,med,acc
low,high,5more,more,big,high,vgood
low,med,2,2,small,low,unacc
low,med,2,2,small,med,unacc
low,med,2,2,small,high,unacc
low,med,2,2,med,low,unacc
low,med,2,2,med,med,unacc
low,med,2,2,med,high,unacc
low,med,2,2,big,low,unacc
low,med,2,2,big,med,unacc
low,med,2,2,big,high,unacc
low,med,2,4,small,low,unacc
low,med,2,4,small,med,acc
low,med,2,4,small,high,good
low,med,2,4,med,low,unacc
low,med,2,4,med,med,acc
low,med,2,4,med,high,good
low,med,2,4,big,low,unacc
low,med,2,4,big,med,good
low,med,2,4,big,high,vgood
low,med,2,more,small,low,unacc
low,med,2,more,small,med,unacc
low,med,2,more,small,high,unacc
low,med,2,more,med,low,unacc
low,med,2,more,med,med,acc
low,med,2,more,med,high,good
low,med,2,more,big,low,unacc
low,med,2,more,big,med,good
low,med,2,more,big,high,vgood
low,med,3,2,small,low,unacc
low,med,3,2,small,med,unacc
low,med,3,2,small,high,unacc
low,med,3,2,med,low,unacc
low,med,3,2,med,med,unacc
low,med,3,2,med,high,unacc
low,med,3,2,big,low,unacc
low,med,3,2,big,med,unacc
low,med,3,2,big,high,unacc
low,med,3,4,small,low,unacc
low,med,3,4,small,med,acc
low,med,3,4,small,high,good
low,med,3,4,med,low,unacc
low,med,3,4,med,med,acc
low,med,3,4,med,high,good
low,med,3,4,big,low,unacc
low,med,3,4,big,med,good
low,med,3,4,big,high,vgood
low,med,3,more,small,low,unacc
low,med,3,more,small,med,acc
low,med,3,more,small,high,good
low,med,3,more,med,low,unacc
low,med,3,more,med,med,good
low,med,3,more,med,high,vgood
low,med,3,more,big,low,unacc
low,med,3,more,big,med,good
low,med,3,more,big,high,vgood
low,med,4,2,small,low,unacc
low,med,4,2,small,med,unacc
low,med,4,2,small,high,unacc
low,med,4,2,med,low,unacc
low,med,4,2,med,med,unacc
low,med,4,2,med,high,unacc
low,med,4,2,big,low,unacc
low,med,4,2,big,med,unacc
low,med,4,2,big,high,unacc
low,med,4,4,small,low,unacc
low,med,4,4,small,med,acc
low,med,4,4,small,high,good
low,med,4,4,med,low,unacc
low,med,4,4,med,med,good
low,med,4,4,med,high,vgood
low,med,4,4,big,low,unacc
low,med,4,4,big,med,good
low,med,4,4,big,high,vgood
low,med,4,more,small,low,unacc
low,med,4,more,small,med,acc
low,med,4,more,small,high,good
low,med,4,more,med,low,unacc
low,med,4,more,med,med,good
low,med,4,more,med,high,vgood
low,med,4,more,big,low,unacc
low,med,4,more,big,med,good
low,med,4,more,big,high,vgood
low,med,5more,2,small,low,unacc
low,med,5more,2,small,med,unacc
low,med,5more,2,small,high,unacc
low,med,5more,2,med,low,unacc
low,med,5more,2,med,med,unacc
low,med,5more,2,med,high,unacc
low,med,5more,2,big,low,unacc
low,med,5more,2,big,med,unacc
low,med,5more,2,big,high,unacc
low,med,5more,4,small,low,unacc
low,med,5more,4,small,med,acc
low,med,5more,4,small,high,good
low,med,5more,4,med,low,unacc
low,med,5more,4,med,med,good
low,med,5more,4,med,high,vgood
low,med,5more,4,big,low,unacc
low,med,5more,4,big,med,good
low,med,5more,4,big,high,vgood
low,med,5more,more,small,low,unacc
low,med,5more,more,small,med,acc
low,med,5more,more,small,high,good
low,med,5more,more,med,low,unacc
low,med,5more,more,med,med,good
low,med,5more,more,med,high,vgood
low,med,5more,more,big,low,unacc
low,med,5more,more,big,med,good
low,med,5more,more,big,high,vgood
low,low,2,2,small,low,unacc
low,low,2,2,small,med,unacc
low,low,2,2,small,high,unacc
low,low,2,2,med,low,unacc
low,low,2,2,med,med,unacc
low,low,2,2,med,high,unacc
low,low,2,2,big,low,unacc
low,low,2,2,big,med,unacc
low,low,2,2,big,high,unacc
low,low,2,4,small,low,unacc
low,low,2,4,small,med,acc
low,low,2,4,small,high,good
low,low,2,4,med,low,unacc
low,low,2,4,med,med,acc
low,low,2,4,med,high,good
low,low,2,4,big,low,unacc
low,low,2,4,big,med,good
low,low,2,4,big,high,vgood
low,low,2,more,small,low,unacc
low,low,2,more,small,med,unacc
low,low,2,more,small,high,unacc
low,low,2,more,med,low,unacc
low,low,2,more,med,med,acc
low,low,2,more,med,high,good
low,low,2,more,big,low,unacc
low,low,2,more,big,med,good
low,low,2,more,big,high,vgood
low,low,3,2,small,low,unacc
low,low,3,2,small,med,unacc
low,low,3,2,small,high,unacc
low,low,3,2,med,low,unacc
low,low,3,2,med,med,unacc
low,low,3,2,med,high,unacc
low,low,3,2,big,low,unacc
low,low,3,2,big,med,unacc
low,low,3,2,big,high,unacc
low,low,3,4,small,low,unacc
low,low,3,4,small,med,acc
low,low,3,4,small,high,good
low,low,3,4,med,low,unacc
low,low,3,4,med,med,acc
low,low,3,4,med,high,good
low,low,3,4,big,low,unacc
low,low,3,4,big,med,good
low,low,3,4,big,high,vgood
low,low,3,more,small,low,unacc
low,low,3,more,small,med,acc
low,low,3,more,small,high,good
low,low,3,more,med,low,unacc
low,low,3,more,med,med,good
low,low,3,more,med,high,vgood
low,low,3,more,big,low,unacc
low,low,3,more,big,med,good
low,low,3,more,big,high,vgood
low,low,4,2,small,low,unacc
low,low,4,2,small,med,unacc
low,low,4,2,small,high,unacc
low,low,4,2,med,low,unacc
low,low,4,2,med,med,unacc
low,low,4,2,med,high,unacc
low,low,4,2,big,low,unacc
low,low,4,2,big,med,unacc
low,low,4,2,big,high,unacc
low,low,4,4,small,low,unacc
low,low,4,4,small,med,acc
low,low,4,4,small,high,good
low,low,4,4,med,low,unacc
low,low,4,4,med,med,good
low,low,4,4,med,high,vgood
low,low,4,4,big,low,unacc
low,low,4,4,big,med,good
low,low,4,4,big,high,vgood
low,low,4,more,small,low,unacc
low,low,4,more,small,med,acc
low,low,4,more,small,high,good
low,low,4,more,med,low,unacc
low,low,4,more,med,med,good
low,low,4,more,med,high,vgood
low,low,4,more,big,low,unacc
low,low,4,more,big,med,good
low,low,4,more,big,high,vgood
low,low,5more,2,small,low,unacc
low,low,5more,2,small,med,unacc
low,low,5more,2,small,high,unacc
low,low,5more,2,med,low,unacc
low,low,5more,2,med,med,unacc
low,low,5more,2,med,high,unacc
low,low,5more,2,big,low,unacc
low,low,5more,2,big,med,unacc
low,low,5more,2,big,high,unacc
low,low,5more,4,small,low,unacc
low,low,5more,4,small,med,acc
low,low,5more,4,small,high,good
low,low,5more,4,med,low,unacc
low,low,5more,4,med,med,good
low,low,5more,4,med,high,vgood
low,low,5more,4,big,low,unacc
low,low,5more,4,big,med,good
low,low,5more,4,big,high,vgood
low,low,5more,more,small,low,unacc
low,low,5more,more,small,med,acc
low,low,5more,more,small,high,good
low,low,5more,more,med,low,unacc
low,low,5more,more,med,med,good
low,low,5more,more,med,high,vgood
low,low,5more,more,big,low,unacc
low,low,5more,more,big,med,good
low,low,5more,more,big,high,vgood
